### ISSUE TITLE
Task: Add Gradle support

### ISSUE THREAD

**Issue by kratz00** [RoffelKartoffel/cmanager#16]
Gradle is a "must have" nowadays, it replaces build tools like Ant or Maven.

I already started working on this and I will use this ticket to keep you in the loop.

**Comment by kratz00** [comment]
Please test https://github.com/kratz00/cmanager/tree/gradle
Feedback is welcome :)
What is missing so far:
- Eclipse integration
- Keeping the version number in sync: _build.gradle_ vs. _src/cmanager/Main.java_

After running _gradlew build_ a jar file is available, which could be shipped directly instead of the jar in the zip file. You can run the jar file like this: _java -jar build/libs/cm-2.0.29.jar_
What is missing here is to replace the jar file name in _src/cmanager/Main.java_ to keep it in sync.
I always wondered how good this idea with the heap size workaround is, if the user would rename the file ... :)

**Comment by kratz00** [comment]
I have updated my gradle branch. The documentation covers the Eclipse integration now.
Please give it a try and report back :smile:

**Comment by kratz00** [comment]
I think the gradle integration is ready. Please have a look before I create a pull request.

**Comment by RoffelKartoffel** [comment]
I have no further experience with gradle, but at least the console version seems to be working as intended ;).

**Comment by kratz00** [comment]
Experience will come by using it :smile: 
Thanks for testing it.

What is missing for your way of working?

For my part, I like that with gradle I can easily setup the project and start developing in Eclipse and if it's time for a new release I just have to run `gradle jar` and that is it.

**Comment by RoffelKartoffel** [comment]
Currently I am not missing anything. Feel free to do a pull request, if you consider it ready.

**Comment by kratz00** [comment]
Done, see https://github.com/RoffelKartoffel/cmanager/pull/18
