### ISSUE TITLE
Crash while loading myfinds.gpx

### ISSUE THREAD

**Issue by Lineflyer** [RoffelKartoffel/cmanager#23]
As reported on #cgeo IRC-channel today.
- I used version 0.2.36
- Tried to load myfinds.gpx freshly downloaded from gc.com
- While loading the file it diaplys "Please stand by.." and then crashes short time after

Screenshot of stacktrace (no C&P from this window):
![2016-09-07 21_25_44-java lang unsupportedclassversionerror](https://cloud.githubusercontent.com/assets/949669/18325549/f73fbd9e-7541-11e6-8890-801de2da2d0b.jpg)

**Comment by Lineflyer** [comment]
Upgrading to the most recent JRE verison 8 solved the problem (for now).

**Comment by RoffelKartoffel** [comment]
The usage of Java 1.7 is now disallowed. Thank you ;)
