### ISSUE TITLE
tut gar nicht: The BROWSE action is not supported

### ISSUE THREAD

**Issue by mirabilos** [RoffelKartoffel/cmanager#27]
![untitled](https://cloud.githubusercontent.com/assets/861078/24430536/4ecf2148-1417-11e7-8ef0-76629be7095b.png)

Screenshot anbei.

**Comment by RoffelKartoffel** [comment]
Please add information about your operating system, java version and browser.

**Comment by mirabilos** [comment]
Jan Murawski dixit:

>Please add information about your operating system, java version and browser.

Debian sid, openjdk-8-jdk 8u121-b13-4

What browser? I ran it with “java -jar …”, no browser involved.
There are several installed, of course.

**Comment by RoffelKartoffel** [comment]
Well, the Java VM tries to launch your default browser with some opencaching.de page so that you can allow the OKAPI token. Do you have a default browser configured? Please configure it if there is none. 
Otherwise: Please tell me your desktop environment and your browser.

**Comment by mirabilos** [comment]
Jan Murawski dixit:

>Well, the Java VM tries to launch your default browser with some
>opencaching.de page so that you can allow the OKAPI token. Do you have
>a default browser configured? Please configure it if there is none.

What is “a default browser”? In Unix/GNU/Linux, there is really no
such thing, so what *precisely* do you mean?

Debian has x-www-browser, but that’s also not called (it’s a working
alternatives system symlink to Konqueror).

How *precisely* does the JRE decide what to run?

>Otherwise: Please tell me your desktop environment and your browser.

No desktop environment, plain X11.

Installed browsers are lynx, links2, dillo, w3m, konqueror, and
all versions of Firefox since 1.5 up to Nightly. At least.

**Comment by RoffelKartoffel** [comment]
A default browser is a user configured URL-display-request dispatcher. "The big" desktop environments support this concept - bare X11 might not. 

I consider your setup a rather rare use case for cmanger and am not interested in researching this. Fell free to supply a workaround patch or report your problem to the java/X11 folks.

**Comment by mirabilos** [comment]
Thanks for your arsehol-ish attitude, but I reported it as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859138 now nevertheless.

**Comment by RoffelKartoffel** [comment]
I'm very happy I could help you.
