### ISSUE TITLE
Unable to restart cmanager

### ISSUE THREAD

**Issue by SammysHP** [RoffelKartoffel/cmanager#28]
I just started cmanager again after a long time without use and got the following error:

```
Unable to restart cmanager. Settings could not be applied.
Expected path: /usr/share/java/cmanager/cmanager.jarcm-0.2.41.jar
```

cmanager is installed to `/usr/share/java/cmanager/cmanager.jar` and I even tried to delete `~/.java/.userPrefs/cmanager/prefs.xml` and `~/.cmanager`.

Started with `java -jar /usr/share/java/cmanager/cmanager.jar` on Arch Linux with Java 1.8.0_121.

**Comment by RoffelKartoffel** [comment]
Fixed with 0.2.42
